### ISSUE TITLE
client glitches

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Cadesim#52]
### Bug 1
Clicking/dragging can occasionally crash the client and/or cause the server to kick the player.

### Bug 2
Closing the server doesn't result in an instant disconnect. This is caused by the wrong thread attempting to call context.dispose() in ClientConnectionTask.java.

```
java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:198)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker$Page$1.dispose(PixmapPacker.java:380)
	at com.badlogic.gdx.graphics.g2d.BitmapFont.dispose(BitmapFont.java:317)
	at com.benberi.cadesim.game.scene.impl.battle.SeaBattleScene.dispose(SeaBattleScene.java:661)
	at com.benberi.cadesim.GameContext.dispose(GameContext.java:384)
	at com.benberi.cadesim.client.ClientConnectionTask.run(ClientConnectionTask.java:65)
```

### Bug 3
Clicking/dragging during the animation phase locks you out from the controls.

**Comment by plaza-in-a-heatwave** [comment]
Bug 1 fixed in [this commit](https://github.com/plaza-in-a-heatwave/Obsidio/commit/f76a27f408af67db534315dd984d45144f79980b)
Bug 2 fixed in [this commit](https://github.com/plaza-in-a-heatwave/Obsidio/commit/3bebcec3f9fcb424f0efcf22aede7339992a831b)

**Comment by plaza-in-a-heatwave** [comment]
Readded Bug 3 - controls lock up.

**Comment by plaza-in-a-heatwave** [comment]
Bug 3 fixed in [this commit](https://github.com/plaza-in-a-heatwave/Obsidio/commit/e8c770a5819367bb77bf2ec78e1c3194891d98a6)

**Comment by plaza-in-a-heatwave** [comment]
Bug 3 still repeatable in 1.9.92 - occasionally all button click/right click controls in the shiphand freeze up and you can only drag onto it.

**Comment by David52920** [comment]
> Bug 1 fixed in [this commit](https://github.com/plaza-in-a-heatwave/Obsidio/commit/f76a27f408af67db534315dd984d45144f79980b)
> Bug 2 fixed as part of [this commit](https://github.com/plaza-in-a-heatwave/Obsidio/commit/3bebcec3f9fcb424f0efcf22aede7339992a831b) **_but reverted in [this commit](https://github.com/plaza-in-a-heatwave/Obsidio/commit/d71628f8c28de1f9aa9bffc5b802c74d66fc8736)_** and reapplied in [this commit](https://github.com/plaza-in-a-heatwave/Obsidio/commit/a54a2e4a13f842c690c752a30622a067f4e41cd9).

Bug 1: I think still occurs, not sure, randomly crashes without a warning.

**Comment by David52920** [comment]
Bug 3: this seems to happen when getting sunk as well occasionally.

**Comment by plaza-in-a-heatwave** [comment]
Created a new issue #80 for bug 3.
